### ISSUE TITLE
Plancke.io guild page doesn't show all players

### ISSUE THREAD

**Issue by jtbuter** [Plancke/hypixel-php#48]
For example [https://plancke.io/hypixel/guild/name/Galex](https://plancke.io/hypixel/guild/name/Galex) only shows 53/115 members.

**Comment by jtbuter** [comment]
It actually appears a different list of players is shown on each refresh of the page. The number of shown players also changes on each page refresh, it fluctuates between 50-60 usernames.

**Comment by Plancke** [comment]
Sorry for the very late response to this, this was caused due to me restructuring the way players were stored I the backend, and I was pulling way more data than required for the guild pages causing it to run out of memory upon display. It should load basically instantly now, some players could be slightly outdated. As soon as they get loaded through stats pages it'll update the "cached" version for the guild page as well though.

**Comment by jtbuter** [comment]
Yes, all is good now. Thanks!
